version: '3'

services:

  clickhouse1:
    image: clickhouse/clickhouse-server:23.4.2.11
    ports:
      - "8123:8123"
      - "9000:9000"
#    environment:
#      CLICKHOUSE_USER: "userC"
#      CLICKHOUSE_PASSWORD: "passC"
#      CLICHOUSE_DB: "dbC"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  chproxy1:
    image: tacyuuhon/clickhouse-chproxy
    ports:
      - "9090:9090"
    volumes:
      - "./chproxy.yml:/opt/config.yml"